apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.secretName | quote }}
                  key: {{ .Values.mysql.rootPasswordKey | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}